name:  04 - Uso de Actions
on:
  push: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: "Checkout Code"
          uses: actions/checkout@v5
        - name: "Node Setup"
          uses: actions/setup-node@v5
        - name: "Install Dependencies"
          working-directory: my-app
          run: |
            npm i